#!/bin/sh
# Very simple dhcp only ifup for Ubuntu

# User configurable
WPA_OPTS="-Dwext"
WPA_CONF="/etc/wpa_supplicant.conf"


echo "$0 $*" >> /tmp/ifup.log # SAM DBG

# systemd 'sends -a --read-environment' to initialize
[ "$1" = "-a" ] && shift 2

iface=${1:-eth0}

ifup() {
    ipaddr -q $iface && { echo "$iface already up"; exit 1; }

    case $iface in
	wlan*) wpa_supplicant -B -i$iface -c$WPA_CONF $WPA_OPTS || exit 1;;
    esac

    sdhcp $iface
}

ifdown() {
    local PID=$(pgrep -f "sdhcp $iface")
    if [ -n "$PID" ]; then
	for i in 1 2 3 4 5 6 7 8 9 10; do
	    kill $PID
	    pgrep -f "sdhcp $iface" > /dev/null || break
	done
    fi

    case $iface in
	wlan*)
	    for i in 1 2 3 4 5; do
		pgrep wpa_supplicant > /dev/null || break
		pkill wpa_supplicant
	    done
	    ;;
    esac

    ipaddr -D $iface
}

ifquery() {
    echo "not yet $0 $*"
}

case "$0" in
    *ifup) ifup;;
    *ifdown) ifdown;;
    *ifquery) ifquery;;
    *) echo "Invalid command $0"; exit 1;;
esac

true # paranoia
